---
title: "Lab 2"
author: "Gareth Tang"
date: "`r format(Sys.time(), '%B %d, %Y %a %I:%M %p')`"
output: html_document
---

# GT Rmarkdown Lab 2 Practice
Load vegan and ggplot2 R packages.
```{r,load-packages,message=FALSE, warning=FALSE}
library("ggplot2")
library("vegan")
```

Load and log transform the dune data set.
```{r, load-transform-dune-data, message=FALSE, warning=FALSE, results='hide'}
data(dune)
dune2 <- dune
dune_log_tranform <- log1p(dune2)
```

Perform non-metric multidimensional scaling on transformed dune data.
```{r, nmds-dune-data, results='hide'}
dune2_nmds <- metaMDS(dune2)
dpoints <- dune2_nmds$point
```

Visualize scaled dune data as a scatter plot. Export plot as a PDF file.
```{r, plot-scaled-dune-data}
dpoints_x <- dpoints[,'MDS1']
dpoints_y <- dpoints[,'MDS2']
nmds_plot <- ggplot() + 
  geom_point(mapping = aes(x = dpoints_x, y = dpoints_y)) + 
  theme_bw() +
  ggtitle('NMDS Plot of Log Transformed Dune Data') + 
  labs(x = 'MDS1', y = 'MDS2')+
  theme(plot.title = element_text(hjust = 0.5))

nmds_plot
ggsave(filename = 'NMDS_dune2_scatter', plot = nmds_plot, device = 'pdf')
```